@endpoint=http://localhost:8080
@fileName=testget

### 查询sql语句
# sqlFileName 不带.sql后缀文件名
#GET {{endpoint}}/api/dev/devops/{fieldName}?key1=value&key2=value2
# 示例
GET {{endpoint}}/api/lc/dosql/{{fileName}}

### 执行sql语句
# sqlFileName 不带.sql后缀文件名
#Post {{endpoint}}/api/dev/devops/{fieldName}?key1=value&key2=value2
# 示例
POST {{endpoint}}/api/lc/dosql/{{fileName}}


### {
###   "fieldName": "示例文件",
###   "sqlFileName": "示例的sql文件",
###   "params": "参数1,参数2，参数3，参数4",
###   "note": "备注一下"
### }

### 查
### /api/adm/apis/{id}
GET {{endpoint}}/api/adm/apis/1

### 增
### /api/adm/apis
POST {{endpoint}}/api/adm/apis

### 删
### /api/adm/apis/{id}
DELETE {{endpoint}}/api/adm/apis/1

### 改
### /api/adm/apis/{id}
PUT {{endpoint}}/api/adm/apis/1

### 分页查询
### /api/adm/apis
GET {{endpoint}}/api/adm/apis?pageNum=1&pageSize=10

### 查看详情
### /api/adm/apis/{id}/detail
GET {{endpoint}}/api/adm/apis/1/detail




