@endpoint = http://localhost:8080
//@endpoint = https://house.cloud.smallsaas.cn

### 获取页面信息（已存在）
GET {{endpoint}}/api/form?id=66666

### 提交页面信息（已存在）
POST {{endpoint}}/api/form/66666
Content-Type: application/json

{  
    "version": "1",
    "name": "allOrder",
    "title": "订单",
    "pageStyle": {
    },
    "loadApi": "",
    "response": {
      "data":"data"
    },
    "request": {
    },
    "moduleContainer":{
    },
    "modules": [
      {
        "type": "autolist",
        "name":"",
        "key":"e59992z8-bb88-a788-9922-1623488775885",
        "container":{
            "height":"",
            "background":"#050E17"
        }
      }
    ],
    "moduleData": {
         "e59992z8-bb88-a788-9922-1623488775885": {
            "loadApi":"/api/u/order",
            "itemNavigation": "",
            "response":{
                "list":"records"
            },
            "request":{
                "default":{
                },
                "ps":"pageSize",
                "pn":"pageNum"
            },
            "itemModule":{
                "name":"orderItem"
            }
        }
    }
}




### 新增：增加 Json 带 tag
POST {{endpoint}}/api/form/demoName/demoTag
Content-Type: application/json

{
  "version": "1",
  "title": "演示-带tag",
  "response": {
    "data": "data"
  }
}

### 新增：分页查询所有页面
GET {{endpoint}}/api/form/forms?pageNum=1&pageSize=10&tag=&search=&pageId=&title=&notes=&content=&jsonName=&createTime=&updateTime=&orderBy=&sort=



