server:
  port: 8081


rocketmq:
  topic: HeartBeat
  name-server: 127.0.0.1:9876
  # ?????
  producer:
    # ??????????????group?????
    group: rocketmq-pro-group
    # ????????,??3000
    sendMessageTimeout: 3000
    # ?????????????2
    retryTimesWhenSendFailed: 2
    # ???????????2
    retryTimesWhenSendAsyncFailed: 2
    # ?????? ??1024*4(4M)
    maxMessageSize: 4096
    # ???????????????broker???false
    retryNextServer: false
    # ?????????4k(1024 * 4)
    compressMessageBodyThreshold: 4096
  consumer:
    group: rocketmq-consumer-group

spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: info
    org.springframework.web: debug
